#!/bin/sh

function baklog ()
{
  let YEAR=`date +%y | sed 's/^0//'`
  let MONTH=`date +%m | sed 's/^0//'`

  if [ $MONTH = 1 ] ; then
    if [ $YEAR = 0 ] ; then
      let YEAR=99
    else
      let YEAR=${YEAR}-1
    fi
    let MONTH=12
  else
    let MONTH=${MONTH}-1
  fi

  if [ $MONTH -lt 10 ] ; then
    MONTH=0${MONTH}
  fi
  if [ $YEAR -lt 10 ] ; then
    YEAR=0${YEAR}
  fi

  zip -9m /bak/husky/log_${YEAR}${MONTH} /husky/log/*.${YEAR}${MONTH}[0-3][0-9]
}

# hpt relink
# hpt notify
# hpt stat

# bakmsg
baklog

