#!/bin/bash
# poll <Zone>:<Net>/<Node>[.<Point>] [<Flavour>]
base=`echo $1|awk '{ sub(/:/, " ") ; sub(/\//, " ") ; sub(/\./, " ")
 if ($1 == "2") { 
  if ($4 == "") { printf "/husky/out/zone/%04x%04x", $2, $3 }
  else { printf "/husky/out/zone/%04x%04x.pnt/0000%04x", $2, $3, $4 } }
 else { 
  if ($4 == "") { printf "/husky/out/zone.%03x/%04x%04x", $1, $2, $3 }
  else { printf "/husky/out/zone.%03x/%04x%04x.pnt/0000%04x", $1, $2, $3, $4 }
 } }'`
if [ "$2" = "" ] ; then flavour=clo ; fi
if [ "$2" = "immediate" ] ; then flavour=ilo ; fi
if [ "$2" = "crash" ] ; then flavour=clo ; fi
if [ "$2" = "normal" ] ; then flavour=flo ; fi
if [ "$2" = "direct" ] ; then flavour=dlo ; fi
if [ "$2" = "hold" ] ; then flavour=hlo ; fi
mkdir -p ${base:0:${#base}-9}
touch ${base}.${flavour}
if [ -f ${base}.sts ] ; then rm ${base}.sts ; fi

if [ -f ${base}.\$\$0 ] ; then rm ${base}.\$\$0 ; fi
