#!/bin/sh

if [ -f /husky/work/pmknl/dolplp.sh ]; then
 rm /husky/work/pmknl/dolplp.sh
 fi
if [ -f /husky/work/pmknl/doldknlp.sh ]; then
 rm /husky/work/pmknl/doldknlp.sh
 fi
if [ -f /husky/work/pmknl/dofido2435pntp.sh ]; then
 rm /husky/work/pmknl/dofido2435pntp.sh
 fi

hatched=0

pmknl linuxnl

pmknl linuxpl
if [ -f /husky/work/pmknl/dolplp.sh ] ; then
 . /husky/work/pmknl/dolplp.sh
 hatched=1
fi

pmknl ldknl
if [ -f /husky/work/pmknl/doldknlp.sh ] ; then
 . /husky/work/pmknl/doldknlp.sh
 hatched=1
fi

pmknl fido2435pnt
if [ -f /husky/work/pmknl/dofido2435pntp.sh ] ; then
 . /husky/work/pmknl/dofido2435pntp.sh
 hatched=1
fi

if [ $hatched = 1 ] ; then
 touch /husky/work/btmail.in
fi

