#!/bin/bash
# request <Zone>:<Net>/<Node>[.<Point>] {<file>}
base=`echo $1|awk '{ sub(/:/, " ") ; sub(/\//, " ") ; sub(/\./, " ")
 if ($1 == "2") { 
  if ($4 == "") { printf "/husky/out/zone/%04x%04x", $2, $3 }
  else { printf "/husky/out/zone/%04x%04x.pnt/0000%04x", $2, $3, $4 } }
 else { 
  if ($4 == "") { printf "/husky/out/zone.%03x/%04x%04x", $1, $2, $3 }
  else { printf "/husky/out/zone.%03x/%04x%04x.pnt/0000%04x", $1, $2, $3, $4 }
 } }'`
mkdir -p ${base:0:${#base}-9}
shift
for f in $* ; do echo $f >> ${base}.req ; done
touch ${base}.dlo

