#!/bin/sh
echo >> /husky/work/echotoss.log
cp /husky/work/echotoss.log /husky/work/echotoss.log.2

hpt scan
protick scan

# lxtrack

progate

hpt pack

# /husky/scripts/send_uue

cp /husky/work/echotoss.log.2 /husky/work/echotoss.log
hpt link

if [ -f /husky/work/echotoss.log ] ; then rm /husky/work/echotoss.log ; fi
if [ -f /husky/work/echotoss.log.2 ] ; then rm /husky/work/echotoss.log.2 ; fi

