# $Id$

# This is "legacy makefile" template to build husky library
# using native compiler and make utility (Usually for win32, OS/2, DOS, ...)
# Copy this file into your work directory; set programs, *PREFIX, *SUFFIX,
# LIBS, _OBJ and above; (possible) edit make rules.
# See also makefile.INC

# Makefile to build XXXXX with ZZZZZ C on YYYYY
# No support for the Husky build environment.

# Uncomment this for compile info for gdb and display more compiler warnings
DEBUG	= -g -pedantic

# Uncomment this for strip all simbols from binaries to reduce file sizes
#STRIP	= -s


## programs ##

# compiler
CC	= gcc
# library tool
AR	= ar
# library indexer
RANLIB	= ranlib
# linker program
LINK	= ld
# archiver program
ARCHIVER= zip
# file removing command
RM	= rm

## file suffixes ##

_C	= .c
_OBJ	= .o
_LIB	= .a
_EXE	= .exe
_DLL	= .dll

## program options ##

# compiler defines
CDEFS	=
# common compiler options
CFLAGS	= -Wall -O3
# linker options
LFLAGS	=
# options for compile only (link is off)
OBJOPT	= -c
# options for build static library
LIBOPT	= -static
# options for build dll
DLLOPT  = -shared
# option for specify output file name
NAMEOPT	= -o
# options for $(AR) program
ARFLAGS	= rs
# options for $(RM) program
RMFLAGS	= -f
# options for archiver
ARCFLAGS= -9 -j

## Library filename elements ##

# Prefix to construct static library name
LIBPREFIX=lib
# Prefix to construct dll name
DLLPREFIX=
# Suffix to construct library name
LIBSUFFIX=xxx
# Suffix to construct dll name
DLLSUFFIX=

## Binary package name ##
PACKAGENAME=$(LIBNAME)$(LIBSUFFIX)

## make directives ##

# rules without dependencies and (possible) actions - prevent warnings
.PHONY:	distclean clean all static dll programs default doc package

## Default make rule ##

default:
	@echo Run 'make dll' to build dll version \($(TARGETDLL), $(PROGRAMS)\)
	@echo Run 'make static' to build static version \($(TARGETLIB), $(PROGRAMS)\)
#	@echo Run 'make dllprograms' to build dll version of programs \($(PROGRAMS)\)
	@echo Run 'make programs' to build static version of programs \($(PROGRAMS)\)
	@echo Run 'make all' to build all above

## include common makefiles part ##

include makefile.inc

# libraries need to build binary file
LIBS	+=

## other, usualy not modify below ##

## Additions (add into end of strings) ##
CFLAGS	+= -I$(H_DIR) $(DEBUG)

## make rules ##

all:	static dll programs

static:	$(TARGETLIB)
dll:	$(TARGETDLL)
programs: $(TARGETLIB) $(PROGRAMS)
dllprograms: $(TARGETDLL) $(PROGRAMS)

%$(_EXE): $(SRC_DIR)%$(_C) $(TARGETLIB)
	$(CC) $(STRIP) $(CFLAGS) $(CDEFS) $(NAMEOPT)$@ $^ $(LIBS)

%$(_OBJ): $(SRC_DIR)%$(_C)
	$(CC) $(CFLAGS) $(CDEFS) $(OBJOPT) $<

$(TARGETLIB):	$(OBJS)
	$(AR) $(ARFLAGS) $@ $?
#	$(RANLIB) $@   # 'ar rs' doing this
	
$(TARGETDLL):	$(OBJS)
	$(CC) $(DLLOPT) $(CFLAGS) $(NAMEOPT)$@ $^


clean:
	-$(RM) $(RMOPT) *$(_OBJ)

distclean:
	-$(RM) $(RMOPT) $(TARGETDLL)
	-$(RM) $(RMOPT) $(TARGETLIB)
	-$(RM) $(RMOPT) $(PROGRAMS)

doc:
	cd ../doc ; make html

package: static programs doc
        @echo XXXXX library v.$(VER) for YYYYY platform > file_id.diz
	@echo (Part of HUSKY Fidonet Software Project) >> file_id.diz
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) $(TARGETLIB) $(PROGRAMS)
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) ../VERSION ../README ../LICENSE
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) ../COPYING ../cvsdate.h
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) ../INSTALL ../HISTORY
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) ../doc/*.html
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) file_id.diz
