# $Id$

# This is "legacy makefile" template to build husky library
# using native compiler and make utility (Usually for win32, OS/2, DOS, ...)
# Copy this file into your work directory; set programs, *PREFIX, *SUFFIX,
# LIBS, _OBJ and above; (possible) edit make rules.
# See also makefile.INC

# Makefile to build XXXXX with ZZZZZ C on YYYYY
# No support for the Husky build environment.

# Uncomment this for compile info for gdb and display more compiler warnings
DEBUG	= -g -pedantic

# Uncomment this for strip all simbols from binaries to reduce file sizes
#STRIP	= -s


## programs ##

# compiler
CC	= gcc
# library tool
AR	= ar
# library indexer
RANLIB	= ranlib
# linker program
LINK	= ld
# archiver program
ARCHIVER= zip
# file removing command
RM	= rm
# create directory command
MKDIR	= mkdir
# remove directory command
RMDIR	= rm
# copy command
CP	= cp
# move command
MV	= mv
# install command
INSTALL	= install


## file suffixes ##

# source file
_C	= .c
# object file
_OBJ	= .o
# binary (executable) file
_EXE	= .exe
# static library
_LIB	= .a
# shared library
_DLL	= .dll
# shared library definitions file (export/import lists & etc.)
_DEF	= .def
# shared library exported list
_EXP	= .exp
# archive (package) file
_ARC	= .zip
# documentation file (".info", ".html", ".div", ...)
_HTML	= .html

## program options ##

# compiler defines
CDEFS	=
# common compiler options
CFLAGS	= -Wall -O3
# linker options
LFLAGS	=
# options for compile only (link is off)
OBJOPT	= -c
# options for build static library
LIBOPT	= -static
# options for build dll
DLLOPT  = -shared
# option for specify output file name
NAMEOPT	= -o
# options for $(AR) program
ARFLAGS	= rs
# options for $(RM) program
RMFLAGS	= -f
# options for archiver
ARCFLAGS= -9 -j
# create directory command options
MKDIROPT= -p
# remove directory command options
RMDIROPT= -rf
# install command options
INSTOPT	= -c
# copy command options
CPOPT	=
# move command options
MVOPT	=


## Library filename elements ##

# Prefix to construct static library name
LIBPREFIX=lib
# Prefix to construct dll name
DLLPREFIX=
# Suffix to construct library name
LIBSUFFIX=xxx
# Suffix to construct dll name
DLLSUFFIX=

## make directives ##

# rules without dependencies and (possible) actions - prevent warnings
.PHONY:	distclean clean all static dll programs default doc package

## Default make rule ##

default:
	@echo Run 'make dll' to build dll version \($(TARGETDLL), $(PROGRAMS)\)
	@echo Run 'make static' to build static version \($(TARGETLIB), $(PROGRAMS)\)
#	@echo Run 'make dllprograms' to build dll version of programs \($(PROGRAMS)\)
	@echo Run 'make programs' to build static version of programs \($(PROGRAMS)\)
	@echo Run 'make all' to build all above

## include common makefiles part ##

include makefile.inc

# libraries need to build binary file
LIBS	+=

## other, usualy not modify below ##

## Additions (add into end of strings) ##
CFLAGS	+= -I$(H_DIR)

## make rules ##

all:	static dll programs

static:	$(TARGETLIB)
dll:	$(TARGETDLL)
programs: $(TARGETLIB) $(PROGRAMS)
dllprograms: $(TARGETDLL) $(PROGRAMS)

%$(_EXE): $(SRC_DIR)%$(_C) $(TARGETLIB)
	$(CC) $(STRIP) $(DEBUG) $(CFLAGS) $(CDEFS) $(NAMEOPT)$@ $^ $(LIBS)

%$(_OBJ): $(SRC_DIR)%$(_C)
	$(CC) $(CFLAGS) $(STRIP) $(DEBUG) $(CDEFS) $(OBJOPT) $<

$(TARGETLIB):	$(OBJS)
	$(AR) $(ARFLAGS) $@ $?
#	$(RANLIB) $@   # 'ar rs' doing this
	
$(TARGETDLL):	$(OBJS)
	$(CC) $(DLLOPT) $(CFLAGS) $(STRIP) $(DEBUG) $(NAMEOPT)$@ $^


clean:
	-$(RM) $(RMOPT) *$(_OBJ)
	-cd ../doc ; make clean

distclean: clean pkgclean
	-$(RM) $(RMOPT) $(TARGETDLL)
	-$(RM) $(RMOPT) $(TARGETLIB)
	-$(RM) $(RMOPT) $(PROGRAMS)
	-cd ../doc ; make distclean

doc:
	cd ../doc ; make html

pkg-doc: pkg-dir
	-$(MKDIR) $(MKDIROPT) $(PACKAGEBASE)/doc
	$(CP) $(CPOPT) ../doc/*$(_HTML) $(PACKAGEBASE)/doc
	
pkg-dir:
	-$(MKDIR) $(MKDIROPT) $(PACKAGEBASE)

$(HEADERS):
	$(CP) $(CPOPT) $@ $(PACKAGEBASE)/$(LIBNAME)

pkg-h: $(HEADERS)

package: static programs doc copy-h pkg-doc
        @echo XXXXX library v.$(VER) for `uname -s` platform > $(PACKAGEBASE)/file_id.diz
	@echo (Part of HUSKY Fidonet Software Project) >> $(PACKAGEBASE)/file_id.diz
	@echo See http://husky.sourceforge.net and/or >> $(PACKAGEBASE)/file_id.diz
	@echo http://sourceforge.net/projects/husky >> $(PACKAGEBASE)/file_id.diz
	$(MKDIR) $(MKDIROPT) $(PACKAGEBASE)
	$(CP) $(CPOPT) $(TARGETLIB) $(PROGRAMS) ../VERSION ../README $(PACKAGEBASE)
	$(CP) $(CPOPT) ../COPYING ../cvsdate.h ../INSTALL ../LICENSE $(PACKAGEBASE)
	$(CP) $(CPOPT) ../HISTORY ../ChangeLog  $(PACKAGEBASE)
	$(MKDIR) $(MKDIROPT) $(PACKAGEBASE)/$(LIBNAME)
	$(CP) $(CPOPT) ../$(H_DIR)/*.h $(PACKAGEBASE)/$(LIBNAME)
	$(ARCHIVER) $(ARCFLAGS) $(PACKAGENAME) $(PACKAGEBASE)/*

pkgclean:
	-$(RM) $(RMOPT) $(PACKAGENAME)
	-$(RM) $(RMOPT) $(PACKAGEBASE)/file_id.diz
	-$(RM) $(RMOPT) $(PACKAGEBASE)/$(LIBNAME)/*
	-$(RMDIR) $(RMDIROPT) $(PACKAGEBASE)/$(LIBNAME)
	-$(RM) $(RMOPT) $(PACKAGEBASE)/*
	-$(RMDIR) $(RMDIROPT) $(PACKAGEBASE)
